import { Plus_Jakarta_Sans } from 'next/font/google';
import "./globals.css";
import Navbars from "@/component/Navbar";
import { Toaster } from 'react-hot-toast';

const jakartaSans = Plus_Jakarta_Sans({ 
  subsets: ['latin'],
  display: 'swap', 
});




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${jakartaSans.className}h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbars/>
        {children}
         <Toaster/>
      </body>
    </html>
  );
}
